//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 5 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    /// Storyboard `Media`.
    static let media = _R.storyboard.media()
    /// Storyboard `Todo`.
    static let todo = _R.storyboard.todo()
    /// Storyboard `Weather`.
    static let weather = _R.storyboard.weather()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Media", bundle: ...)`
    static func media(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.media)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Todo", bundle: ...)`
    static func todo(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.todo)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Weather", bundle: ...)`
    static func weather(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.weather)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    /// Color `AccentColor`.
    static let accentColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "AccentColor")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentColor(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentColor.name)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 9 images.
  struct image {
    /// Image `icons8-back`.
    static let icons8Back = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-back")
    /// Image `icons8-check_circle`.
    static let icons8Check_circle = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-check_circle")
    /// Image `icons8-checked_checkbox`.
    static let icons8Checked_checkbox = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-checked_checkbox")
    /// Image `icons8-kodi`.
    static let icons8Kodi = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-kodi")
    /// Image `icons8-round`.
    static let icons8Round = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-round")
    /// Image `icons8-save`.
    static let icons8Save = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-save")
    /// Image `icons8-todo_list`.
    static let icons8Todo_list = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-todo_list")
    /// Image `icons8-unchecked_checkbox`.
    static let icons8Unchecked_checkbox = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-unchecked_checkbox")
    /// Image `icons8-wind_speed_38-42`.
    static let icons8Wind_speed_3842 = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-wind_speed_38-42")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-back", bundle: ..., traitCollection: ...)`
    static func icons8Back(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Back, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-check_circle", bundle: ..., traitCollection: ...)`
    static func icons8Check_circle(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Check_circle, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-checked_checkbox", bundle: ..., traitCollection: ...)`
    static func icons8Checked_checkbox(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Checked_checkbox, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-kodi", bundle: ..., traitCollection: ...)`
    static func icons8Kodi(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Kodi, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-round", bundle: ..., traitCollection: ...)`
    static func icons8Round(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Round, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-save", bundle: ..., traitCollection: ...)`
    static func icons8Save(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Save, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-todo_list", bundle: ..., traitCollection: ...)`
    static func icons8Todo_list(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Todo_list, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-unchecked_checkbox", bundle: ..., traitCollection: ...)`
    static func icons8Unchecked_checkbox(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Unchecked_checkbox, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-wind_speed_38-42", bundle: ..., traitCollection: ...)`
    static func icons8Wind_speed_3842(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Wind_speed_3842, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    struct uiApplicationSceneManifest {
      static let _key = "UIApplicationSceneManifest"
      static let uiApplicationSupportsMultipleScenes = false

      struct uiSceneConfigurations {
        static let _key = "UISceneConfigurations"

        struct uiWindowSceneSessionRoleApplication {
          struct defaultConfiguration {
            static let _key = "Default Configuration"
            static let uiSceneConfigurationName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneConfigurationName") ?? "Default Configuration"
            static let uiSceneDelegateClassName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate"
            static let uiSceneStoryboardFile = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneStoryboardFile") ?? "Main"

            fileprivate init() {}
          }

          fileprivate init() {}
        }

        fileprivate init() {}
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.nib` struct is generated, and contains static references to 1 nibs.
  struct nib {
    /// Nib `TodoTableViewCell`.
    static let todoTableViewCell = _R.nib._TodoTableViewCell()

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "TodoTableViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.todoTableViewCell) instead")
    static func todoTableViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.todoTableViewCell)
    }
    #endif

    static func todoTableViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> TodoTableViewCell? {
      return R.nib.todoTableViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? TodoTableViewCell
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct nib {
    struct _TodoTableViewCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "TodoTableViewCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> TodoTableViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? TodoTableViewCell
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }
  #endif

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try main.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try media.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try todo.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try weather.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = BaseNavigationController

      let baseNavigationController = StoryboardViewControllerResource<BaseNavigationController>(identifier: "BaseNavigationController")
      let bundle = R.hostingBundle
      let menuTabbarViewController = StoryboardViewControllerResource<MenuTabbarViewController>(identifier: "MenuTabbarViewController")
      let name = "Main"

      func baseNavigationController(_: Void = ()) -> BaseNavigationController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: baseNavigationController)
      }

      func menuTabbarViewController(_: Void = ()) -> MenuTabbarViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: menuTabbarViewController)
      }

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.main().baseNavigationController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'baseNavigationController' could not be loaded from storyboard 'Main' as 'BaseNavigationController'.") }
        if _R.storyboard.main().menuTabbarViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'menuTabbarViewController' could not be loaded from storyboard 'Main' as 'MenuTabbarViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct media: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let mediaViewController = StoryboardViewControllerResource<MediaViewController>(identifier: "MediaViewController")
      let name = "Media"

      func mediaViewController(_: Void = ()) -> MediaViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: mediaViewController)
      }

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.media().mediaViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'mediaViewController' could not be loaded from storyboard 'Media' as 'MediaViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct todo: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "Todo"
      let todoInfoViewController = StoryboardViewControllerResource<TodoInfoViewController>(identifier: "TodoInfoViewController")
      let todoViewController = StoryboardViewControllerResource<TodoViewController>(identifier: "TodoViewController")

      func todoInfoViewController(_: Void = ()) -> TodoInfoViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: todoInfoViewController)
      }

      func todoViewController(_: Void = ()) -> TodoViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: todoViewController)
      }

      static func validate() throws {
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "plus") == nil { throw Rswift.ValidationError(description: "[R.swift] System image named 'plus' is used in storyboard 'Todo', but couldn't be loaded.") } }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.todo().todoInfoViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'todoInfoViewController' could not be loaded from storyboard 'Todo' as 'TodoInfoViewController'.") }
        if _R.storyboard.todo().todoViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'todoViewController' could not be loaded from storyboard 'Todo' as 'TodoViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct weather: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "Weather"
      let weatherViewController = StoryboardViewControllerResource<WeatherViewController>(identifier: "WeatherViewController")

      func weatherViewController(_: Void = ()) -> WeatherViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: weatherViewController)
      }

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.weather().weatherViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'weatherViewController' could not be loaded from storyboard 'Weather' as 'WeatherViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
