//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 6 storyboards.
  struct storyboard {
    /// Storyboard `Alert`.
    static let alert = _R.storyboard.alert()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    /// Storyboard `Media`.
    static let media = _R.storyboard.media()
    /// Storyboard `Todo`.
    static let todo = _R.storyboard.todo()
    /// Storyboard `Weather`.
    static let weather = _R.storyboard.weather()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Alert", bundle: ...)`
    static func alert(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.alert)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Media", bundle: ...)`
    static func media(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.media)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Todo", bundle: ...)`
    static func todo(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.todo)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Weather", bundle: ...)`
    static func weather(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.weather)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    /// Color `AccentColor`.
    static let accentColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "AccentColor")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentColor(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentColor.name)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.file` struct is generated, and contains static references to 2 files.
  struct file {
    /// Resource file `ca_dao_hoc_tap.rtf`.
    static let ca_dao_hoc_tapRtf = Rswift.FileResource(bundle: R.hostingBundle, name: "ca_dao_hoc_tap", pathExtension: "rtf")
    /// Resource file `lao_dong_san_xuat.rtf`.
    static let lao_dong_san_xuatRtf = Rswift.FileResource(bundle: R.hostingBundle, name: "lao_dong_san_xuat", pathExtension: "rtf")

    /// `bundle.url(forResource: "ca_dao_hoc_tap", withExtension: "rtf")`
    static func ca_dao_hoc_tapRtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.ca_dao_hoc_tapRtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "lao_dong_san_xuat", withExtension: "rtf")`
    static func lao_dong_san_xuatRtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.lao_dong_san_xuatRtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 33 images.
  struct image {
    /// Image `NoData`.
    static let noData = Rswift.ImageResource(bundle: R.hostingBundle, name: "NoData")
    /// Image `bakery_pin`.
    static let bakery_pin = Rswift.ImageResource(bundle: R.hostingBundle, name: "bakery_pin")
    /// Image `bakery`.
    static let bakery = Rswift.ImageResource(bundle: R.hostingBundle, name: "bakery")
    /// Image `bar_pin`.
    static let bar_pin = Rswift.ImageResource(bundle: R.hostingBundle, name: "bar_pin")
    /// Image `bar`.
    static let bar = Rswift.ImageResource(bundle: R.hostingBundle, name: "bar")
    /// Image `cafe_pin`.
    static let cafe_pin = Rswift.ImageResource(bundle: R.hostingBundle, name: "cafe_pin")
    /// Image `cafe`.
    static let cafe = Rswift.ImageResource(bundle: R.hostingBundle, name: "cafe")
    /// Image `coffee`.
    static let coffee = Rswift.ImageResource(bundle: R.hostingBundle, name: "coffee")
    /// Image `driving_pin`.
    static let driving_pin = Rswift.ImageResource(bundle: R.hostingBundle, name: "driving_pin")
    /// Image `driving`.
    static let driving = Rswift.ImageResource(bundle: R.hostingBundle, name: "driving")
    /// Image `filter`.
    static let filter = Rswift.ImageResource(bundle: R.hostingBundle, name: "filter")
    /// Image `generic`.
    static let generic = Rswift.ImageResource(bundle: R.hostingBundle, name: "generic")
    /// Image `grocery_or_supermarket_pin`.
    static let grocery_or_supermarket_pin = Rswift.ImageResource(bundle: R.hostingBundle, name: "grocery_or_supermarket_pin")
    /// Image `grocery_or_supermarket`.
    static let grocery_or_supermarket = Rswift.ImageResource(bundle: R.hostingBundle, name: "grocery_or_supermarket")
    /// Image `icon_me`.
    static let icon_me = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon_me")
    /// Image `icons8-airport_arrow_baggage_direction_luggage_move_62`.
    static let icons8Airport_arrow_baggage_direction_luggage_move_62 = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-airport_arrow_baggage_direction_luggage_move_62")
    /// Image `icons8-back`.
    static let icons8Back = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-back")
    /// Image `icons8-check_circle`.
    static let icons8Check_circle = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-check_circle")
    /// Image `icons8-checked_checkbox`.
    static let icons8Checked_checkbox = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-checked_checkbox")
    /// Image `icons8-done`.
    static let icons8Done = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-done")
    /// Image `icons8-kodi`.
    static let icons8Kodi = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-kodi")
    /// Image `icons8-ok`.
    static let icons8Ok = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-ok")
    /// Image `icons8-round`.
    static let icons8Round = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-round")
    /// Image `icons8-save`.
    static let icons8Save = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-save")
    /// Image `icons8-todo_list`.
    static let icons8Todo_list = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-todo_list")
    /// Image `icons8-unchecked_checkbox`.
    static let icons8Unchecked_checkbox = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-unchecked_checkbox")
    /// Image `icons8-wind_speed_38-42`.
    static let icons8Wind_speed_3842 = Rswift.ImageResource(bundle: R.hostingBundle, name: "icons8-wind_speed_38-42")
    /// Image `loginBG`.
    static let loginBG = Rswift.ImageResource(bundle: R.hostingBundle, name: "loginBG")
    /// Image `restaurant_pin`.
    static let restaurant_pin = Rswift.ImageResource(bundle: R.hostingBundle, name: "restaurant_pin")
    /// Image `restaurant`.
    static let restaurant = Rswift.ImageResource(bundle: R.hostingBundle, name: "restaurant")
    /// Image `rw-logo`.
    static let rwLogo = Rswift.ImageResource(bundle: R.hostingBundle, name: "rw-logo")
    /// Image `rwdevcon-bg`.
    static let rwdevconBg = Rswift.ImageResource(bundle: R.hostingBundle, name: "rwdevcon-bg")
    /// Image `walking`.
    static let walking = Rswift.ImageResource(bundle: R.hostingBundle, name: "walking")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "NoData", bundle: ..., traitCollection: ...)`
    static func noData(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.noData, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "bakery", bundle: ..., traitCollection: ...)`
    static func bakery(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.bakery, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "bakery_pin", bundle: ..., traitCollection: ...)`
    static func bakery_pin(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.bakery_pin, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "bar", bundle: ..., traitCollection: ...)`
    static func bar(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.bar, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "bar_pin", bundle: ..., traitCollection: ...)`
    static func bar_pin(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.bar_pin, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "cafe", bundle: ..., traitCollection: ...)`
    static func cafe(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.cafe, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "cafe_pin", bundle: ..., traitCollection: ...)`
    static func cafe_pin(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.cafe_pin, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "coffee", bundle: ..., traitCollection: ...)`
    static func coffee(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.coffee, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "driving", bundle: ..., traitCollection: ...)`
    static func driving(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.driving, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "driving_pin", bundle: ..., traitCollection: ...)`
    static func driving_pin(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.driving_pin, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "filter", bundle: ..., traitCollection: ...)`
    static func filter(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.filter, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "generic", bundle: ..., traitCollection: ...)`
    static func generic(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.generic, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "grocery_or_supermarket", bundle: ..., traitCollection: ...)`
    static func grocery_or_supermarket(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.grocery_or_supermarket, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "grocery_or_supermarket_pin", bundle: ..., traitCollection: ...)`
    static func grocery_or_supermarket_pin(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.grocery_or_supermarket_pin, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icon_me", bundle: ..., traitCollection: ...)`
    static func icon_me(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icon_me, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-airport_arrow_baggage_direction_luggage_move_62", bundle: ..., traitCollection: ...)`
    static func icons8Airport_arrow_baggage_direction_luggage_move_62(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Airport_arrow_baggage_direction_luggage_move_62, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-back", bundle: ..., traitCollection: ...)`
    static func icons8Back(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Back, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-check_circle", bundle: ..., traitCollection: ...)`
    static func icons8Check_circle(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Check_circle, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-checked_checkbox", bundle: ..., traitCollection: ...)`
    static func icons8Checked_checkbox(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Checked_checkbox, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-done", bundle: ..., traitCollection: ...)`
    static func icons8Done(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Done, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-kodi", bundle: ..., traitCollection: ...)`
    static func icons8Kodi(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Kodi, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-ok", bundle: ..., traitCollection: ...)`
    static func icons8Ok(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Ok, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-round", bundle: ..., traitCollection: ...)`
    static func icons8Round(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Round, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-save", bundle: ..., traitCollection: ...)`
    static func icons8Save(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Save, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-todo_list", bundle: ..., traitCollection: ...)`
    static func icons8Todo_list(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Todo_list, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-unchecked_checkbox", bundle: ..., traitCollection: ...)`
    static func icons8Unchecked_checkbox(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Unchecked_checkbox, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icons8-wind_speed_38-42", bundle: ..., traitCollection: ...)`
    static func icons8Wind_speed_3842(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icons8Wind_speed_3842, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "loginBG", bundle: ..., traitCollection: ...)`
    static func loginBG(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.loginBG, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "restaurant", bundle: ..., traitCollection: ...)`
    static func restaurant(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.restaurant, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "restaurant_pin", bundle: ..., traitCollection: ...)`
    static func restaurant_pin(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.restaurant_pin, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "rw-logo", bundle: ..., traitCollection: ...)`
    static func rwLogo(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.rwLogo, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "rwdevcon-bg", bundle: ..., traitCollection: ...)`
    static func rwdevconBg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.rwdevconBg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "walking", bundle: ..., traitCollection: ...)`
    static func walking(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.walking, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    struct uiApplicationSceneManifest {
      static let _key = "UIApplicationSceneManifest"
      static let uiApplicationSupportsMultipleScenes = false

      struct uiSceneConfigurations {
        static let _key = "UISceneConfigurations"

        struct uiWindowSceneSessionRoleApplication {
          struct defaultConfiguration {
            static let _key = "Default Configuration"
            static let uiSceneConfigurationName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneConfigurationName") ?? "Default Configuration"
            static let uiSceneDelegateClassName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate"
            static let uiSceneStoryboardFile = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneStoryboardFile") ?? "Main"

            fileprivate init() {}
          }

          fileprivate init() {}
        }

        fileprivate init() {}
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.nib` struct is generated, and contains static references to 4 nibs.
  struct nib {
    /// Nib `MarkerInfoView`.
    static let markerInfoView = _R.nib._MarkerInfoView()
    /// Nib `MediaDetailTableViewCell`.
    static let mediaDetailTableViewCell = _R.nib._MediaDetailTableViewCell()
    /// Nib `MediaTableViewCell`.
    static let mediaTableViewCell = _R.nib._MediaTableViewCell()
    /// Nib `TodoTableViewCell`.
    static let todoTableViewCell = _R.nib._TodoTableViewCell()

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "MarkerInfoView", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.markerInfoView) instead")
    static func markerInfoView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.markerInfoView)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "MediaDetailTableViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.mediaDetailTableViewCell) instead")
    static func mediaDetailTableViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.mediaDetailTableViewCell)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "MediaTableViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.mediaTableViewCell) instead")
    static func mediaTableViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.mediaTableViewCell)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "TodoTableViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.todoTableViewCell) instead")
    static func todoTableViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.todoTableViewCell)
    }
    #endif

    static func markerInfoView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> MarkerInfoView? {
      return R.nib.markerInfoView.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? MarkerInfoView
    }

    static func mediaDetailTableViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> MediaDetailTableViewCell? {
      return R.nib.mediaDetailTableViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? MediaDetailTableViewCell
    }

    static func mediaTableViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> MediaTableViewCell? {
      return R.nib.mediaTableViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? MediaTableViewCell
    }

    static func todoTableViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> TodoTableViewCell? {
      return R.nib.todoTableViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? TodoTableViewCell
    }

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 7 localization keys.
    struct localizable {
      /// en translation: All
      ///
      /// Locales: en
      static let all = Rswift.StringResource(key: "all", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en"], comment: nil)
      /// en translation: Completed
      ///
      /// Locales: en
      static let completed = Rswift.StringResource(key: "completed", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en"], comment: nil)
      /// en translation: Favorite
      ///
      /// Locales: en
      static let favorite = Rswift.StringResource(key: "favorite", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en"], comment: nil)
      /// en translation: Incompleted
      ///
      /// Locales: en
      static let incompleted = Rswift.StringResource(key: "incompleted", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en"], comment: nil)
      /// en translation: Media
      ///
      /// Locales: en
      static let media = Rswift.StringResource(key: "media", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en"], comment: nil)
      /// en translation: Todo
      ///
      /// Locales: en
      static let todo = Rswift.StringResource(key: "todo", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en"], comment: nil)
      /// en translation: Weather
      ///
      /// Locales: en
      static let weather = Rswift.StringResource(key: "weather", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en"], comment: nil)

      /// en translation: All
      ///
      /// Locales: en
      static func all(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("all", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "all"
        }

        return NSLocalizedString("all", bundle: bundle, comment: "")
      }

      /// en translation: Completed
      ///
      /// Locales: en
      static func completed(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("completed", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "completed"
        }

        return NSLocalizedString("completed", bundle: bundle, comment: "")
      }

      /// en translation: Favorite
      ///
      /// Locales: en
      static func favorite(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("favorite", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "favorite"
        }

        return NSLocalizedString("favorite", bundle: bundle, comment: "")
      }

      /// en translation: Incompleted
      ///
      /// Locales: en
      static func incompleted(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("incompleted", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "incompleted"
        }

        return NSLocalizedString("incompleted", bundle: bundle, comment: "")
      }

      /// en translation: Media
      ///
      /// Locales: en
      static func media(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("media", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "media"
        }

        return NSLocalizedString("media", bundle: bundle, comment: "")
      }

      /// en translation: Todo
      ///
      /// Locales: en
      static func todo(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("todo", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "todo"
        }

        return NSLocalizedString("todo", bundle: bundle, comment: "")
      }

      /// en translation: Weather
      ///
      /// Locales: en
      static func weather(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("weather", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "weather"
        }

        return NSLocalizedString("weather", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct nib {
    struct _MarkerInfoView: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "MarkerInfoView"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> MarkerInfoView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? MarkerInfoView
      }

      fileprivate init() {}
    }

    struct _MediaDetailTableViewCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "MediaDetailTableViewCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> MediaDetailTableViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? MediaDetailTableViewCell
      }

      fileprivate init() {}
    }

    struct _MediaTableViewCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "MediaTableViewCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> MediaTableViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? MediaTableViewCell
      }

      fileprivate init() {}
    }

    struct _TodoTableViewCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "TodoTableViewCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> TodoTableViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? TodoTableViewCell
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }
  #endif

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try alert.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try main.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try media.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try todo.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try weather.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct alert: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "Alert"
      let showAlertViewController = StoryboardViewControllerResource<ShowAlertViewController>(identifier: "ShowAlertViewController")

      func showAlertViewController(_: Void = ()) -> ShowAlertViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: showAlertViewController)
      }

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.alert().showAlertViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'showAlertViewController' could not be loaded from storyboard 'Alert' as 'ShowAlertViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = LoginViewController

      let baseNavigationController = StoryboardViewControllerResource<BaseNavigationController>(identifier: "BaseNavigationController")
      let bundle = R.hostingBundle
      let loginViewController = StoryboardViewControllerResource<LoginViewController>(identifier: "LoginViewController")
      let menuTabbarViewController = StoryboardViewControllerResource<MenuTabbarViewController>(identifier: "MenuTabbarViewController")
      let name = "Main"

      func baseNavigationController(_: Void = ()) -> BaseNavigationController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: baseNavigationController)
      }

      func loginViewController(_: Void = ()) -> LoginViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: loginViewController)
      }

      func menuTabbarViewController(_: Void = ()) -> MenuTabbarViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: menuTabbarViewController)
      }

      static func validate() throws {
        if UIKit.UIImage(named: "loginBG", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'loginBG' is used in storyboard 'Main', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.main().baseNavigationController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'baseNavigationController' could not be loaded from storyboard 'Main' as 'BaseNavigationController'.") }
        if _R.storyboard.main().loginViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'loginViewController' could not be loaded from storyboard 'Main' as 'LoginViewController'.") }
        if _R.storyboard.main().menuTabbarViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'menuTabbarViewController' could not be loaded from storyboard 'Main' as 'MenuTabbarViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct media: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let mediaDetailViewController = StoryboardViewControllerResource<MediaDetailViewController>(identifier: "MediaDetailViewController")
      let mediaViewController = StoryboardViewControllerResource<MediaViewController>(identifier: "MediaViewController")
      let name = "Media"

      func mediaDetailViewController(_: Void = ()) -> MediaDetailViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: mediaDetailViewController)
      }

      func mediaViewController(_: Void = ()) -> MediaViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: mediaViewController)
      }

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.media().mediaDetailViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'mediaDetailViewController' could not be loaded from storyboard 'Media' as 'MediaDetailViewController'.") }
        if _R.storyboard.media().mediaViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'mediaViewController' could not be loaded from storyboard 'Media' as 'MediaViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct todo: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "Todo"
      let todoInfoViewController = StoryboardViewControllerResource<TodoInfoViewController>(identifier: "TodoInfoViewController")
      let todoViewController = StoryboardViewControllerResource<TodoViewController>(identifier: "TodoViewController")

      func todoInfoViewController(_: Void = ()) -> TodoInfoViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: todoInfoViewController)
      }

      func todoViewController(_: Void = ()) -> TodoViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: todoViewController)
      }

      static func validate() throws {
        if UIKit.UIImage(named: "NoData", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'NoData' is used in storyboard 'Todo', but couldn't be loaded.") }
        if UIKit.UIImage(named: "icons8-ok", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'icons8-ok' is used in storyboard 'Todo', but couldn't be loaded.") }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "plus") == nil { throw Rswift.ValidationError(description: "[R.swift] System image named 'plus' is used in storyboard 'Todo', but couldn't be loaded.") } }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.todo().todoInfoViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'todoInfoViewController' could not be loaded from storyboard 'Todo' as 'TodoInfoViewController'.") }
        if _R.storyboard.todo().todoViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'todoViewController' could not be loaded from storyboard 'Todo' as 'TodoViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct weather: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "Weather"
      let weatherViewController = StoryboardViewControllerResource<WeatherViewController>(identifier: "WeatherViewController")

      func weatherViewController(_: Void = ()) -> WeatherViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: weatherViewController)
      }

      static func validate() throws {
        if UIKit.UIImage(named: "filter", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'filter' is used in storyboard 'Weather', but couldn't be loaded.") }
        if UIKit.UIImage(named: "icon_me", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'icon_me' is used in storyboard 'Weather', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.weather().weatherViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'weatherViewController' could not be loaded from storyboard 'Weather' as 'WeatherViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
